item {
  id: 1
  name: 'brakeshoe'
}

 

item {
  id: 2
  name: 'coilcover'
}

 

item {
  id: 3
  name: 'doublecheckvalve'
}

 

item {
  id: 4
  name: 'efknuckle'
}

 

item {
  id: 5
  name: 'spring'
}

 

item {
  id: 6
  name: 'throttlebody'
}

 

item {
  id: 7
  name: 'turbocharger'
}